### ISSUE TITLE
Usermod command is incorrect

### ISSUE THREAD

**Issue by D-u-c-k-s-e-l** [yehuthi/linuxflip#3]
In the README, there is a suggestion to add yourself to the group `input` with the following command:

```sh
sudo usermod -a input $USER
```

This fails, and returns the help menu.

Instead, the command should be:

```sh
sudo usermod -G input -a $USER
```

**Comment by yehuthi** [comment]
Fixed 55ba23c784d77a15eb6ce3136c6f86d2dd2aa788, thank you!
